-- Seed Initial Admin User (Real bcrypt hash for '2010OVIE')
INSERT INTO users (username, password_hash) 
VALUES ('admin', '$2b$10$vI8aWBnW3fID.ZQ4/zo1G.u.K5m7p92ldGxad68LJZdL17lhWy')
ON CONFLICT (username) DO NOTHING;

-- Ensure unique index exists on members.full_name to support ON CONFLICT DO NOTHING
CREATE UNIQUE INDEX IF NOT EXISTS members_full_name_idx ON members (full_name);

-- Seed the 61 Altar Servers safely with ON CONFLICT DO NOTHING
INSERT INTO members (full_name, status) VALUES
('ABIGAIL', 'active'),
('ADENUGA TEMISAN', 'active'),
('AJI JOSEPH', 'active'),
('AKINDELE DANIELLA', 'active'),
('AKINDELE JOHN', 'active'),
('AKWAJI JAMES', 'active'),
('ALIYU NICHOLAS', 'active'),
('ARINZE', 'active'),
('AYANWU NAOMI', 'active'),
('AYINLA ANTHONY', 'active'),
('BENEDICT', 'active'),
('BETHEL', 'active'),
('CHIDERA', 'active'),
('CHIGOZIE', 'active'),
('CHIOMA', 'active'),
('CHUKWU JOSEPH', 'active'),
('COLLINS', 'active'),
('DESMOND', 'active'),
('EBUBE', 'active'),
('EMERE', 'active'),
('FRANKLYN', 'active'),
('IDOKO JUDE', 'active'),
('IKENWE SAMUEL', 'active'),
('IKELOHA SONIA', 'active'),
('JOHN JESSE', 'active'),
('JOHN PAUL', 'active'),
('KENECHUKWU JEREMIAH', 'active'),
('MARVELOUS', 'active'),
('MARY MATTHEW', 'active'),
('MIRACLE', 'active'),
('NZEBUKA PAUL', 'active'),
('NZEBUKA SANDRA', 'active'),
('OBIDINMA EMMANUEL', 'active'),
('OGWURUMBA PATRICK', 'active'),
('OKEKE CHIMA', 'active'),
('OKALIME EMMANUEL', 'active'),
('OLATUNJI ANTHONY', 'active'),
('OLAYI EMMANUELLA', 'active'),
('OLAYI IMMACULATA', 'active'),
('OLAYI PETER', 'active'),
('OYINDAMOLA', 'active'),
('OVERAH MICHAEL', 'active'),
('PASCAL', 'active'),
('PETER ICHIMI', 'active'),
('PETER NNANA', 'active'),
('RAPHAEL CHINEDU', 'active'),
('RAYMOND', 'active'),
('SAMUEL ANAYO', 'active'),
('SOLOMON EMMANUEL', 'active'),
('THOMAS', 'active'),
('UBA NAOMI', 'active'),
('UCHECHUKWUMBA MICHAEL', 'active'),
('UCHECHUKWUMBA PRAISE', 'active'),
('UDEH VALENTINE', 'active'),
('UGOCHUKWU MICHAEL (JNR)', 'active'),
('UGOCHUKWU MICHAEL (SNR)', 'active'),
('UGONNA', 'active'),
('UGWU AUGUSTINE', 'active'),
('UGWU AUGUSTINA', 'active'),
('UGWU SOMTO', 'active'),
('UMENSOFOR CHIBIKE', 'active')
ON CONFLICT (full_name) DO NOTHING;